/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/EditableRow`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchDrawer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PersonCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PersonDetailForm`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/pdfExport`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ActionFab`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchFilterDrawer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/DateSortModals`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/pdfGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/types`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/EditableRow`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/SearchDrawer`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/PersonCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/PersonDetailForm`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/pdfExport`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ProfileHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ActionFab`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/SearchHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/SearchFilterDrawer`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/DateSortModals`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/pdfGenerator`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/types${`?${string}` | `#${string}` | ''}` | `/../src/components/EditableRow${`?${string}` | `#${string}` | ''}` | `/../src/components/SearchDrawer${`?${string}` | `#${string}` | ''}` | `/../src/components/PersonCard${`?${string}` | `#${string}` | ''}` | `/../src/components/PersonDetailForm${`?${string}` | `#${string}` | ''}` | `/../src/utils/pdfExport${`?${string}` | `#${string}` | ''}` | `/../src/components/ProfileHeader${`?${string}` | `#${string}` | ''}` | `/../src/components/ActionFab${`?${string}` | `#${string}` | ''}` | `/../src/components/SearchHeader${`?${string}` | `#${string}` | ''}` | `/../src/components/SearchFilterDrawer${`?${string}` | `#${string}` | ''}` | `/../src/components/DateSortModals${`?${string}` | `#${string}` | ''}` | `/../src/utils/pdfGenerator${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/EditableRow`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchDrawer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PersonCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PersonDetailForm`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/pdfExport`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ActionFab`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchFilterDrawer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/DateSortModals`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/pdfGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
